export const LOCATIONS_LOADING = 'LOCATIONS_LOADING';
export const LOCATIONS_FAILED = 'LOCATIONS_FAILED';
export const ADD_LOCATIONS = 'ADD_LOCATIONS';

export const EQUIPMENT_LOADING = 'EQUIPMENT_LOADING';
export const EQUIPMENT_FAILED = 'EQUIPMENT_FAILED';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT';

export const ADD_SERVICE = 'ADD_SERVICE';
export const SERVICE_LOADING = 'SERVICE_LOADING';
export const SERVICE_FAILED = 'SERVICE_FAILED';